openapi: 3.0.3
info:
  title: Swagger Go api - OpenAPI 3.0
  version: 1.0.11
servers:
  - url: http://localhost:4343/
paths:
  /users:
    post:
      tags:
        - users
      summary: Add a new users
      description: Add a new users
      operationId: addusers
      requestBody:
        description: Create a new users
        required: true
        content:
          application/json:
            schema:
              required:
                - "name"
                - "passportNumber"
                - "passportSeries"
              properties:
                name:
                  description: Username
                  example: Test-0
                  type: string
                passportNumber:
                  type: integer
                  format: int
                  example: 1122
                passportSeries:
                  type: integer
                  format: int
                  example: "123456"
              type: object
      responses:
        "200":
          description: Successful operation
        "400":
          description: Invalid input
        "422":
          description: Validation exception
    get:
      tags:
        - users
      summary: get users
      description: Returns list
      responses:
        "200":
          description: successful operation
        "400":
          description: Invalid route
    put:
      tags:
        - users
      summary: update user
      description: update user
      requestBody:
        description: Create a new users
        required: true
        content:
          application/json:
            schema:
              required:
                - "id"
              properties:
                id:
                  type: string
                  example: 0c91ff10-95a9-4a1a-b5b8-90956f95e919
                name:
                  description: Username
                  example: Test-1
                  type: string
              type: object
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
          required: true
        "400":
          description: Invalid input
        "422":
          description: Validation exception
  /users/{id}:
    get:
      tags:
        - user
      summary: get user
      description: Returns one user
      parameters:
        - in: path
          name: id
          schema:
            type: string
            example: 0c91ff10-95a9-4a1a-b5b8-90956f95e919
          description: User
      responses:
        "200":
          description: successful operation
        "400":
          description: Invalid ID supplied
  /users/time:
    post:
      tags:
        - time
      summary: get time spent by user on tasks
      description: calculates time for all user tasks
      requestBody:
        description: get time spent by user on tasks
        required: true
        content:
          application/json:
            schema:
              required:
                - "id"
              properties:
                id:
                  type: string
                  example: e0b929ef-2972-470e-b5b2-664522248cd4
              type: object
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
          required: true
        "400":
          description: Invalid ID supplied
        "422":
          description: Validation exception
  /tasks:
    get:
      tags:
        - tasks
      summary: get tasks
      description: Returns list
      responses:
        "200":
          description: successful operation
        "400":
          description: Invalid route
  /tasks/{id}:
    get:
      tags:
        - task
      summary: get task
      description: Returns one task
      parameters:
        - in: path
          name: id
          schema:
            type: string
            example: ef646391-e15b-4a51-aa16-27ffa7f51bfd
          description: Task
      responses:
        "200":
          description: successful operation
        "400":
          description: Invalid ID supplied
  /tasks/start:
    post:
      tags:
        - start
      summary: sets the task start time
      description: the time intervals between starts and pauses/closing are calculated
      requestBody:
        description: if the task has already been launched, the date is not updated
        required: true
        content:
          application/json:
            schema:
              required:
                - "id"
              properties:
                id:
                  type: string
                  example: ef646391-e15b-4a51-aa16-27ffa7f51bfd
              type: object
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
          required: true
        "400":
          description: Invalid ID supplied
        "422":
          description: Validation exception
  /tasks/stop:
    post:
      tags:
        - stop
      summary: sets the pause time in task execution
      description: the time intervals between starts and pauses/closing are calculated
      requestBody:
        description: if the task has already been launched, the date is not updated
        required: true
        content:
          application/json:
            schema:
              required:
                - "id"
              properties:
                id:
                  type: string
                  example: ef646391-e15b-4a51-aa16-27ffa7f51bfd
              type: object
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
          required: true
        "400":
          description: Invalid ID supplied
        "422":
          description: Validation exception
  /tasks/complete:
    post:
      tags:
        - complete
      summary: sets the pause time in task execution
      description: the time intervals between starts and pauses/closing are calculated
      requestBody:
        description: if the task has already been closed it cannot be started
        required: true
        content:
          application/json:
            schema:
              required:
                - "id"
              properties:
                id:
                  type: string
                  example: ef646391-e15b-4a51-aa16-27ffa7f51bfd
              type: object
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
          required: true
        "400":
          description: Invalid ID supplied
        "422":
          description: Validation exception
